[[Parts]]
url="https://www.canadacomputers.com/product_info.php?cPath=4_64_1969&item_id=138215"
scraper="canadacomputers"
name="CanadaComputers: AMD Ryzen 5 3600"

[[Parts]]
url="http://megacomputer.ca/index.php/main/Product/CPUA0173"
scraper="megacomputer"
name="MegaComputer: AMD Ryzen 5 3600"

[[Parts]]
url="https://www.memoryexpress.com/Products/MX77406"
scraper="memoryexpress"
name="MemoryExpress: AMD Ryzen 5 3600"
